type: carla
camera_metadata_path: intersection_spu/metadata/intersection_lehr.yaml
maximal_distance_in_heatmap: 20
heatmap_sparsity: 5
maximal_median_projection_error: 50
maximal_camera_distance_to_driven_path: 30
maximal_sensor_range: 125
filter_negative_heights: true
minimal_sequence_length: 4
minimal_image_track_length: 100.0
minimal_world_track_length: 3.0
use_ransac: true
maximal_projection_error: 8
maximal_ransac_iterations: 500
tracker_decay_after: 8
use_yolov5_labels: false
outlier_score_threshold: 0.5
overlap_score_threshold: 0.45
rotational_similarity_threshold: 0.95
dbscan_eps: 8.0
dbscan_min_samples: 2
vehicle_length: 0.0
vehicle_width: 0.0
vehicle_height: 0.0
imu_x: 0.0
imu_y: 0.0
imu_z: 0.0
camera_width: 1920
camera_height: 1200
camera_fov: 90.0
camera_x: -62.32
camera_y: -39.29
camera_z: 10.60
camera_pitch: -28.64
camera_yaw: 46.65
minimal_distance_to_image_edge: 5
lifting_threshold: 0.1
