type: intersection_spu
camera_metadata_path: trailer/metadata/trailer.yaml
maximal_distance_in_heatmap: 20
heatmap_sparsity: 5
maximal_median_projection_error: 50
maximal_camera_distance_to_driven_path: 10000
maximal_sensor_range: 125
filter_negative_heights: true
minimal_sequence_length: 4
minimal_image_track_length: 100.0
minimal_world_track_length: 3.0
use_ransac: true
maximal_projection_error: 8
maximal_ransac_iterations: 500
tracker_decay_after: 8
use_yolov5_labels: false
outlier_score_threshold: 0.5
overlap_score_threshold: 0.45
rotational_similarity_threshold: 0.95
dbscan_eps: 5.0
dbscan_min_samples: 2
vehicle_length: 4.895
vehicle_width: 1.854
vehicle_height: 1.474
imu_x: 1.1925
imu_y: 0.927
imu_z: 0.548
minimal_distance_to_image_edge: 20
lifting_threshold: 0.035
grid_tile_size: 0.5